import './_group.css'
import React, { useState } from 'react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import { Activity, AlertTriangle, ArrowRight, BarChart3, Bell, BookOpen, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronDown, CircleDollarSign, ClipboardCheck, Clock3, FileSearch, FileText, GitBranch, GitMerge, LayoutDashboard, LogOut, Mail, Plus, Receipt, Search, Settings, ShieldAlert, ShieldCheck, SlidersHorizontal, Users, X } from 'lucide-react'

const C = { petrol:'#176b6b', steel:'#55758a', ink:'#172a31', muted:'#7d898d', ok:'#4f806d', warn:'#a57d37', risk:'#ad6255' }
const groups = [
  { name:'CORE', items:[['Dashboard',LayoutDashboard],['My Actions',ClipboardCheck],['Clients',Users],['Matters',BriefcaseBusiness]] },
  { name:'INTELLIGENCE', items:[['Legal AI',BarChart3],['Research',FileSearch],['Knowledge Base',BookOpen],['Conflict Check',GitMerge]] },
  { name:'DOCUMENTS', items:[['Documents',FileText],['Templates',FileText],['Email',Mail]] },
  { name:'OPERATIONS', items:[['Workflows',GitBranch],['Calendar',CalendarDays],['Appointments',Users],['Tasks',ClipboardCheck],['Time Tracking',Clock3],['Billing',Receipt]] },
  { name:'COMPLIANCE', items:[['FICA Compliance',ShieldAlert],['Audit Logs',FileSearch],['Admin',ShieldCheck]] },
] as const
const pipeline = [['Lead',8,'#718b9a'],['Conflict check',5,C.warn],['Approved',11,C.steel],['Active',47,C.ok],['Review',9,'#777d92'],['Completed',23,'#628b7d'],['Closed',31,'#526a75']] as const
const revenue = [{m:'Feb',v:1477000},{m:'Mar',v:1846000},{m:'Apr',v:2074000},{m:'May',v:2300000},{m:'Jun',v:2582000},{m:'Jul',v:2840000}]
const workload = [['AK','Andile Khumalo',14],['ND','Nothando Dlamini',11],['SM','Sipho Mokoena',9],['LN','Lindiwe Nkosi',7],['TS','Thabo Sithole',6],['ZM','Zanele Mthembu',4]] as const
const activity = [['Nothando Dlamini','created Matter M-2024-0391 for Sasol Ltd','8m',FileText,C.steel],['System','conflict check completed — no conflicts found','22m',GitMerge,C.ok],['Sipho Mokoena','time entry logged — 3.5h on M-2024-0367','55m',Activity,C.muted],['Zanele Mthembu','client contact added — Standard Bank Treasury','2h',Users,C.petrol],['Andile Khumalo','approved Matter M-2024-0388 for commencement','3h',CheckCircle2,C.ok],['Lindiwe Nkosi','document NDA-Draft-v3.docx marked high-risk by AI','5h',AlertTriangle,C.risk]] as const
function money(v:number){ return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(v) }
function Panel({title,accent=C.petrol,children}:{title:string;accent?:string;children:React.ReactNode}){ return <section className="prod-panel"><div className="prod-panel-head"><i style={{background:accent}} />{title}</div><div className="prod-panel-body">{children}</div></section> }
function Metric({label,value,color=C.ink,onClick}:{label:string;value:string|number;color?:string;onClick:()=>void}){ return <button className="prod-metric" style={{borderLeftColor:color}} onClick={onClick}><span>{label}</span><b style={{color}}>{value}</b><ArrowRight size={12}/></button> }
function PaperPetrolProduction(){
  const [selected,setSelected]=useState('Dashboard')
  const [dismissed,setDismissed]=useState(false)
  const [toast,setToast]=useState('')
  const notify=(text:string)=>{ setToast(text); window.setTimeout(()=>setToast(''),2200) }
  const action=(text='Opening workspace queue')=>notify(text)
  return <div className="apz-production"><div className="prod-shell">
    <aside className="prod-sidebar">
      <div className="prod-brand"><div className="prod-mark">A</div><div><b>APZ Legal</b><small>LEGAL OPERATING SYSTEM</small></div></div>
      <div className="prod-profile"><div className="prod-avatar">AK</div><div><b>Andile Khumalo</b><small>Managing Partner</small></div><ChevronDown size={13} style={{marginLeft:'auto',color:C.muted}} /></div>
      <div className="prod-search"><Search size={13}/><span>Search workspace</span><kbd>⌘K</kbd></div>
      <nav className="prod-nav prod-scroll">{groups.map(group=><div key={group.name}><div className="prod-nav-group">{group.name}</div>{group.items.map(([label,Icon])=><button key={label} className={selected===label?'active':''} onClick={()=>{setSelected(label);notify(`${label} selected`)}}><Icon size={14}/><span>{label}</span>{label==='My Actions'&&<em>4</em>}{label==='Conflict Check'&&<em>5</em>}{label==='Documents'&&<em>12</em>}{label==='FICA Compliance'&&<em>3</em>}</button>)}</div>)}</nav>
      <div className="prod-side-bottom"><button className="prod-new" onClick={()=>action('New matter form ready')}><Plus size={14}/>New matter</button><div className="prod-side-actions"><button onClick={()=>notify('Settings selected')}><Settings size={13}/>Settings</button><button onClick={()=>notify('Signed out')} aria-label="Sign out"><LogOut size={13}/></button></div></div>
    </aside>
    <main className="prod-content">
      <header className="prod-topbar"><div className="prod-crumb"><span>APZ Legal</span><ArrowRight size={11}/><strong>{selected}</strong></div><div className="prod-top-actions"><button className="prod-icon" onClick={()=>notify('Search opened')} aria-label="Search"><Search size={14}/></button><button className="prod-icon" onClick={()=>notify('Notifications opened')} aria-label="Notifications"><Bell size={14}/><i className="prod-notice"/></button><button className="prod-icon" onClick={()=>notify('Attention queue opened')} aria-label="Attention"><AlertTriangle size={14}/></button><span className="prod-role">Managing Partner</span></div></header>
      <div className="prod-main prod-scroll">
        <div className="prod-heading"><div><span className="prod-eyebrow">OPERATIONS OVERVIEW</span><h1>Good morning, Andile</h1><p>Monday, 18 November 2024 <span>·</span> Firm overview</p></div><div className="prod-heading-actions"><button className="prod-control" onClick={()=>notify('Showing today')}><CalendarDays size={13}/>Today<ChevronDown size={12}/></button><button className="prod-control" onClick={()=>notify('Department filter opened')}><SlidersHorizontal size={13}/>All departments<ChevronDown size={12}/></button><button className="prod-control primary" onClick={()=>action('New matter form ready')}><Plus size={13}/>New matter</button></div></div>
        {!dismissed&&<div className="prod-alert"><div className="prod-alert-head"><Bell size={14} color={C.risk}/><b>6 items requiring your attention</b><span className="prod-badge risk">3 critical</span><span className="prod-badge warn">3 warnings</span><button onClick={()=>setDismissed(true)} aria-label="Dismiss alerts"><X size={14}/></button></div><div className="prod-alert-items">{[['1 client blocked — FICA incomplete',C.risk],['2 expired FICA documents',C.risk],['2 matters flagged at risk',C.risk],['2 AI documents flagged high-risk',C.warn],['FICA at 87% — below threshold',C.warn],['4 tasks overdue',C.warn]].map(([t,c])=><button className="prod-alert-item" key={t as string} onClick={()=>action()}><i style={{background:c as string}}/><span style={{color:c as string}}>{t}</span><ArrowRight size={12}/></button>)}</div></div>}
        <div className="prod-kpis">{[[BriefcaseBusiness,'Active matters','47','+4 from last month',C.petrol],[GitMerge,'Conflict checks','5','Awaiting review',C.warn],[ShieldCheck,'FICA compliant','87%','Firm threshold 90%',C.warn],[CircleDollarSign,'Unbilled hours','38h','Across active matters',C.petrol],[ClipboardCheck,'Overdue tasks','4','Requires attention',C.risk]].map(([Icon,label,value,sub,color])=>{const KpiIcon=Icon as React.ElementType;return <button className="prod-kpi" key={String(label)} onClick={()=>action()}><div className="prod-kpi-label"><KpiIcon size={13} style={{color:color as string}}/>{String(label)}</div><strong style={{color:color as string}}>{String(value)}</strong><small>{String(sub)}</small></button>})}</div>
        <div className="prod-grid">
          <div className="prod-col"><Panel title={`Matter pipeline · ${pipeline.reduce((a,p)=>a+p[1],0)} total`}><div>{pipeline.map(([n,v,c])=><div className="prod-pipe-row" key={n}><span className="prod-pipe-label"><i style={{background:c}}/>{n}</span><div className="prod-bar"><i style={{width:`${Number(v)/134*100}%`,background:c}}/></div></div>)}</div><button className="prod-footer" onClick={()=>action('Matters workspace opened')}>View all matters<ArrowRight size={12} style={{marginLeft:'auto'}}/></button></Panel><Panel title="Revenue · 6-month trend" accent={C.steel}><div className="prod-revenue"><div><strong>{money(2840000)}</strong><span>↑ YTD</span></div><div><b>{money(620000)}</b><small>OUTSTANDING</small></div></div><div className="prod-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue}><defs><linearGradient id="prodFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={C.petrol} stopOpacity=".22"/><stop offset="100%" stopColor={C.petrol} stopOpacity="0"/></linearGradient></defs><XAxis dataKey="m" tick={{fill:C.muted,fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:C.ink,border:'0',fontSize:10,color:'#f7f4eb'}} formatter={(v)=>money(Number(v))}/><Area dataKey="v" stroke={C.petrol} fill="url(#prodFill)" strokeWidth={2} dot={false}/></AreaChart></ResponsiveContainer></div></Panel></div>
          <div className="prod-col"><Panel title="Requires approval" accent={C.warn}>{[['Matters awaiting commencement',6,C.steel],['Conflict checks pending',5,C.warn],['Documents awaiting approval',12,C.warn],['AI high-risk documents',2,C.risk],['Matters flagged at risk',2,C.risk]].map(([label,value,color])=><Metric key={label as string} label={label as string} value={value as number} color={color as string} onClick={()=>action()}/>)}</Panel><Panel title="Team workload">{workload.map(([initials,name,count])=><div className="prod-person" key={name}><div className="prod-avatar">{initials}</div><div className="prod-person-main"><div><span>{name}</span><b>{count}</b></div><div className="prod-bar"><i style={{width:`${Number(count)/14*100}%`,background:C.petrol}}/></div></div></div>)}</Panel></div>
          <div className="prod-col"><Panel title="Recent activity" accent={C.steel}><div>{activity.map(([who,desc,time,Icon,color])=><div className="prod-activity" key={desc}><Icon size={13} style={{color}}/><p><b>{who}</b> {desc}</p><time>{time}</time></div>)}</div><div className="prod-quick">{['All matters','Conflicts','Billing','Audit log'].map(x=><button key={x} onClick={()=>notify(`${x} opened`)}>{x}</button>)}</div></Panel></div>
        </div>
      </div>
    </main>
    {toast&&<div className="prod-toast">{toast}</div>}
  </div></div>
}
export { PaperPetrolProduction }
export default PaperPetrolProduction