import { Router, type IRouter } from "express";
import healthRouter       from "./health";
import authRouter         from "./auth";
import clientsRouter      from "./clients";
import mattersRouter      from "./matters";
import documentsRouter    from "./documents";
import tasksRouter        from "./tasks";
import conflictsRouter    from "./conflicts";
import timeRouter         from "./time";
import billingRouter      from "./billing";
import knowledgeRouter    from "./knowledge";
import aiRouter           from "./ai";
import researchRouter     from "./research";
import auditRouter        from "./audit";
import dashboardRouter    from "./dashboard";
import appointmentsRouter from "./appointments";
import visitorsRouter     from "./visitors";
import ficaRouter         from "./fica";
import workflowsRouter    from "./workflows";
import adminRouter        from "./admin";
import storageRouter      from "./storage";
import providerOperationsRouter from "./provider-operations";
import emailsRouter      from "./emails";
import microsoftRouter   from "./microsoft";
import productivityRouter from "./productivity";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(clientsRouter);
router.use(mattersRouter);
router.use(documentsRouter);
router.use(tasksRouter);
router.use(conflictsRouter);
router.use(timeRouter);
router.use(billingRouter);
router.use(knowledgeRouter);
router.use(researchRouter);
router.use(aiRouter);
router.use(auditRouter);
router.use(dashboardRouter);
router.use(appointmentsRouter);
router.use(visitorsRouter);
router.use(ficaRouter);
router.use(workflowsRouter);
router.use(adminRouter);
router.use(storageRouter);
router.use(providerOperationsRouter);
router.use(emailsRouter);
router.use(microsoftRouter);
router.use(productivityRouter);

export default router;
