// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/apz-dashboard-familiar-polish/FamiliarDashboard.tsx": () => import("../components/mockups/apz-dashboard-familiar-polish/FamiliarDashboard.tsx"),
  "./components/mockups/apz-dashboard-ink-brass/InkBrassDashboard.tsx": () => import("../components/mockups/apz-dashboard-ink-brass/InkBrassDashboard.tsx"),
  "./components/mockups/apz-dashboard-legal-slate/LegalSlateDashboard.tsx": () => import("../components/mockups/apz-dashboard-legal-slate/LegalSlateDashboard.tsx"),
  "./components/mockups/apz-dashboard-ink-brass-dark/InkBrassDarkDashboard.tsx": () => import("../components/mockups/apz-dashboard-ink-brass-dark/InkBrassDarkDashboard.tsx"),
  "./components/mockups/apz-dashboard-minimal-ink/MinimalInkDashboard.tsx": () => import("../components/mockups/apz-dashboard-minimal-ink/MinimalInkDashboard.tsx"),
  "./components/mockups/apz-dashboard-paper-teal/PaperTealDashboard.tsx": () => import("../components/mockups/apz-dashboard-paper-teal/PaperTealDashboard.tsx"),
  "./components/mockups/apz-dashboard-refinement/RefinedDashboard.tsx": () => import("../components/mockups/apz-dashboard-refinement/RefinedDashboard.tsx"),
  "./components/mockups/apz-paper-petrol-production/PaperPetrolProduction.tsx": () => import("../components/mockups/apz-paper-petrol-production/PaperPetrolProduction.tsx"),
  "./components/mockups/legal-ai-redesign/Current.tsx": () => import("../components/mockups/legal-ai-redesign/Current.tsx"),
  "./components/mockups/legal-ai-redesign/Redesigned.tsx": () => import("../components/mockups/legal-ai-redesign/Redesigned.tsx")
};
