import './_group.css'
import React, { useState } from 'react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import {
  Activity, AlertTriangle, ArrowRight, BarChart3, Bell, BriefcaseBusiness, CalendarDays,
  CheckCircle2, ChevronDown, CircleDollarSign, ClipboardCheck, FileSearch, FileText,
  GitMerge, LayoutDashboard, LogOut, Plus, Receipt, Search, Settings, ShieldCheck,
  SlidersHorizontal, Users, X,
} from 'lucide-react'

const C = { bg:'#07111f', sidebar:'#091525', surface:'#0c1a2b', raised:'#102138', line:'#1d314b', soft:'#142842', ink:'#dce9f7', muted:'#8298b3', quiet:'#5a7392', blue:'#6f90e8', cyan:'#62c4d5', ok:'#6ea88f', warn:'#c6a064', risk:'#c8797d' }
const pipeline = [{n:'Lead',v:8,c:'#5d7fa5'},{n:'Conflict check',v:5,c:C.warn},{n:'Approved',v:11,c:C.blue},{n:'Active',v:47,c:C.ok},{n:'Review',v:9,c:'#887eb3'},{n:'Completed',v:23,c:'#709b87'},{n:'Closed',v:31,c:'#54708e'}]
const workload = [['AK','Andile Khumalo',14],['ND','Nothando Dlamini',11],['SM','Sipho Mokoena',9],['LN','Lindiwe Nkosi',7],['TS','Thabo Sithole',6],['ZM','Zanele Mthembu',4]] as const
const activity: Array<[string,string,string,React.ElementType,string]> = [
  ['Nothando Dlamini','created Matter M-2024-0391 for Sasol Ltd','8m',FileText,C.blue],
  ['System','conflict check completed — no conflicts found','22m',GitMerge,C.ok],
  ['Sipho Mokoena','time entry logged — 3.5h on M-2024-0367','55m',Activity,C.muted],
  ['Zanele Mthembu','client contact added — Standard Bank Treasury','2h',Users,C.cyan],
  ['Andile Khumalo','approved Matter M-2024-0388 for commencement','3h',CheckCircle2,C.ok],
  ['Lindiwe Nkosi','document NDA-Draft-v3.docx marked high-risk by AI','5h',AlertTriangle,C.risk],
]
const revenue = [{m:'Feb',v:1477000},{m:'Mar',v:1846000},{m:'Apr',v:2074000},{m:'May',v:2300000},{m:'Jun',v:2582000},{m:'Jul',v:2840000}]
const nav = [
  [LayoutDashboard,'Dashboard'],[BriefcaseBusiness,'Matters'],[Users,'Clients'],[GitMerge,'Conflicts'],[FileText,'Documents'],[ShieldCheck,'FICA'],[Receipt,'Billing'],[FileSearch,'Audit'],[BarChart3,'Reports'],
] as const
function money(v:number){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(v)}
function Section({title, accent=C.blue, children}:{title:string;accent?:string;children:React.ReactNode}){return <section className="panel"><div className="section-title"><i style={{background:accent}} />{title}</div>{children}</section>}
function Metric({label,value,color=C.ink,active=false}:{label:string;value:string|number;color?:string;active?:boolean}){return <button className="metric hoverable" style={{borderLeftColor:active?color:'transparent'}}><span style={{color:active?color:C.muted}}>{label}</span><b className="mono" style={{color}}>{value}</b><ArrowRight size={12} /></button>}
function Kpi({icon:Icon,label,value,sub,color=C.blue}:{icon:React.ElementType;label:string;value:string|number;sub:string;color?:string}){return <button className="kpi hoverable"><div className="kpi-label"><Icon size={14} style={{color}} />{label}</div><strong style={{color}}>{value}</strong><small>{sub}</small></button>}
function Sidebar(){const [open,setOpen]=useState(false); return <aside className="sidebar"><div className="brand"><div className="brand-mark"><ShieldCheck size={19}/></div><div><b>APZ Legal</b><small>MATTER MANAGEMENT</small></div></div><div className="profile"><div className="avatar">AK</div><div><b>Andile Khumalo</b><small>Managing Partner</small></div><ChevronDown size={14}/></div><div className="side-search"><Search size={14}/><span>Search workspace</span><kbd>⌘K</kbd></div><nav className="nav-list">{nav.map(([Icon,label],i)=><button key={label} className={`nav-item ${i===0?'selected':''}`} onClick={()=>setOpen(!open)}><Icon size={16}/><span>{label}</span>{label==='Conflicts'&&<em style={{color:C.warn}}>5</em>}{label==='Documents'&&<em>12</em>}{label==='FICA'&&<em style={{color:C.risk}}>3</em>}</button>)}</nav><div className="side-bottom"><button className="new-matter"><Plus size={15}/>New matter</button><div className="side-foot"><button><Settings size={14}/>Settings</button><button aria-label="Log out"><LogOut size={14}/></button></div></div>{open&&<div className="toast"><X size={13} onClick={()=>setOpen(false)}/>Navigation preview only</div>}</aside>}
function AlertStrip(){const [dismissed,setDismissed]=useState(false); if(dismissed)return null; const items=[['1 client blocked — FICA incomplete',C.risk],['2 expired FICA documents',C.risk],['2 matters flagged at risk',C.risk],['2 AI documents flagged high-risk',C.warn],['FICA at 87% — below threshold',C.warn],['4 tasks overdue',C.warn]]; return <div className="alert-strip"><div className="alert-head"><Bell size={15} style={{color:C.risk}}/><b>6 items requiring your attention</b><span className="badge risk">3 critical</span><span className="badge warn">3 warnings</span><button onClick={()=>setDismissed(true)} aria-label="Dismiss alerts"><X size={15}/></button></div><div className="alert-items">{items.map(([t,c])=><button key={t} className="alert-item hoverable"><i style={{background:c}}/><span style={{color:c}}>{t}</span><ArrowRight size={12}/></button>)}</div></div>}
function Pipeline(){const total=pipeline.reduce((a,p)=>a+p.v,0); return <Section title={`Matter pipeline · ${total} total`}><div className="pipeline">{pipeline.map(p=><div className="pipe-row" key={p.n}><span className="pipe-label"><i style={{background:p.c}}/>{p.n}</span><div className="bar"><i style={{width:`${p.v/total*100}%`,background:p.c}}/></div><b className="mono">{p.v}</b></div>)}</div><button className="footer-link">View all matters <ArrowRight size={12}/></button></Section>}
function Approvals(){return <Section title="Requires approval" accent={C.warn}><Metric label="Matters awaiting commencement" value={6} color={C.blue} active/><Metric label="Conflict checks pending" value={5} color={C.warn} active/><Metric label="Documents awaiting approval" value={12} color={C.warn} active/><Metric label="AI high-risk documents" value={2} color={C.risk} active/><Metric label="Matters flagged at risk" value={2} color={C.risk} active/></Section>}
function Workload(){return <Section title="Team workload"><div className="workload">{workload.map(([initials,name,count])=><div className="person" key={name}><div className="avatar small">{initials}</div><div className="person-main"><div><span>{name}</span><b className="mono">{count}</b></div><div className="bar"><i style={{width:`${count/14*100}%`,background:`linear-gradient(90deg,${C.blue},${C.cyan})`}}/></div></div></div>)}</div></Section>}
function Revenue(){return <Section title="Revenue · 6-month trend" accent={C.cyan}><div className="revenue-head"><div><strong>{money(2840000)}</strong><span style={{color:C.ok}}>↗ YTD</span></div><div><b style={{color:C.warn}}>{money(620000)}</b><small>OUTSTANDING</small></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue}><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={C.blue} stopOpacity=".28"/><stop offset="100%" stopColor={C.cyan} stopOpacity="0"/></linearGradient></defs><XAxis dataKey="m" tick={{fill:C.quiet,fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:C.raised,border:`1px solid ${C.line}`,fontSize:11}} formatter={(v)=>money(Number(v))}/><Area dataKey="v" stroke={C.blue} fill="url(#fill)" strokeWidth={2} dot={false}/></AreaChart></ResponsiveContainer></div></Section>}
function ActivityFeed(){return <Section title="Recent activity" accent={C.cyan}><div className="activity">{activity.map(([who,desc,time,Icon,color],i)=><div className="activity-row" key={desc}><Icon size={14} style={{color}}/><p><b>{who}</b> {desc}</p><time className="mono">{time}</time></div>)}</div><div className="quick-links">{['All matters','Conflicts','Billing','Audit log'].map(x=><button key={x}>{x}</button>)}</div></Section>}
export function FamiliarDashboard(){return <div className="apz-familiar"><div className="shell"><Sidebar/><main className="content"><header className="header"><div><h1>Good morning, Andile</h1><p>Monday, 18 November 2024 <span>·</span> Firm overview</p></div><div className="header-actions"><button className="icon-button"><CalendarDays size={16}/></button><button className="icon-button"><Bell size={16}/><i/></button><button className="filter"><SlidersHorizontal size={14}/> All departments <ChevronDown size={13}/></button></div></header><div className="main"><div className="context-row"><div><span className="eyebrow">OPERATIONS OVERVIEW</span><p>Review the firm’s open work and exceptions before your first meeting.</p></div><button className="date-button">Today <ChevronDown size={13}/></button></div><AlertStrip/><div className="kpis"><Kpi icon={BriefcaseBusiness} label="Active matters" value={47} sub="+4 from last month"/><Kpi icon={GitMerge} label="Conflict checks" value={5} sub="Awaiting review" color={C.warn}/><Kpi icon={ShieldCheck} label="FICA compliant" value="87%" sub="Firm threshold 90%" color={C.warn}/><Kpi icon={CircleDollarSign} label="Unbilled hours" value="38h" sub="Across active matters" color={C.cyan}/><Kpi icon={ClipboardCheck} label="Overdue tasks" value={4} sub="Requires attention" color={C.risk}/></div><div className="content-grid"><div className="left-col"><Pipeline/><Revenue/></div><div className="middle-col"><Approvals/><Workload/></div><div className="right-col"><ActivityFeed/></div></div></div></main></div></div>}
export default FamiliarDashboard