#!/usr/bin/env bash
# Provision Lexora shared resources on apztdg.com (idempotent).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INFRA="/home/ubuntu/infra"
ENV_FILE="$ROOT/.env"

log() { echo "[provision] $*"; }

# ── Load shared infra secrets ─────────────────────────────────────────────────
if [[ ! -f "$INFRA/.env" ]]; then
  echo "Missing $INFRA/.env — start shared infra first."
  exit 1
fi

set -a
# shellcheck disable=SC1091
source "$INFRA/.env"
set +a

# ── Ensure platform stacks are up ─────────────────────────────────────────────
if ! docker network inspect infra_shared >/dev/null 2>&1; then
  log "Starting shared infra..."
  (cd "$INFRA" && ./scripts/up.sh)
fi

if ! docker network inspect ai-models_default >/dev/null 2>&1; then
  log "Starting ai-models stack..."
  (cd /home/ubuntu/ai-models && docker compose up -d ollama qdrant)
fi

# ── Postgres (shared) ─────────────────────────────────────────────────────────
DB_PASSWORD=""
if docker exec infra-postgres psql -U postgres -tAc "SELECT 1 FROM pg_database WHERE datname='lexora'" | grep -q 1; then
  log "Postgres database 'lexora' already exists."
  if [[ -f "$ENV_FILE" ]] && grep -q '^DATABASE_URL=' "$ENV_FILE"; then
    DB_PASSWORD="$(grep '^DATABASE_URL=' "$ENV_FILE" | sed -n 's|.*://lexora_app:\([^@]*\)@.*|\1|p')"
  fi
else
  log "Creating Postgres database 'lexora'..."
  OUT="$(cd "$INFRA" && ./scripts/create-app-db.sh lexora)"
  echo "$OUT"
  DB_PASSWORD="$(echo "$OUT" | sed -n 's/^  Password:             //p')"
fi

if [[ -z "$DB_PASSWORD" ]]; then
  log "Could not determine DB password — set DATABASE_URL in .env manually."
  DB_PASSWORD="CHANGE_ME"
fi

# ── MinIO bucket (shared) ─────────────────────────────────────────────────────
log "Ensuring MinIO bucket 'lexora'..."
docker run --rm --network infra_shared \
  -e "MC_HOST_local=http://${MINIO_ROOT_USER}:${MINIO_ROOT_PASSWORD}@minio:9000" \
  minio/mc:latest mb --ignore-existing "local/lexora" 2>/dev/null \
  || log "MinIO bucket step skipped (mc unavailable — create 'lexora' bucket manually if needed)."

# ── Qdrant collections (shared, prefixed) ─────────────────────────────────────
log "Ensuring Qdrant collections..."
bash "$ROOT/scripts/setup-qdrant-collections.sh"

# ── Write .env ────────────────────────────────────────────────────────────────
log "Writing $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/provision.sh — shared apztdg.com platform
APP_URL=https://lexora.apztdg.com
NODE_ENV=production
FIRM_NAME=Smith & Partners Inc.
FIRM_JURISDICTION=ZA

DATABASE_URL=postgresql://lexora_app:${DB_PASSWORD}@postgres:5432/lexora
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/3

S3_ENDPOINT=http://minio:9000
S3_BUCKET=lexora
S3_ACCESS_KEY=${MINIO_ROOT_USER}
S3_SECRET_KEY=${MINIO_ROOT_PASSWORD}

QDRANT_URL=http://qdrant:6333
QDRANT_COLLECTION_PREFIX=lexora_

OLLAMA_BASE_URL=http://ollama:11434/v1
OLLAMA_TEXT_MODEL=qwen2.5:32b
OLLAMA_EMBED_MODEL=nomic-embed-text
AI_MAX_CONCURRENCY=1
EOF

chmod 600 "$ENV_FILE"
log "Provision complete."
log "  Postgres: lexora @ postgres:5432"
log "  Redis:    DB index 3"
log "  MinIO:    bucket lexora"
log "  Qdrant:   lexora_* collections"
log "  Ollama:   shared (concurrency=1)"
