import './_group.css'
import React, { useState } from 'react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import { Activity, AlertTriangle, ArrowRight, BarChart3, Bell, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronDown, CircleDollarSign, ClipboardCheck, FileSearch, FileText, GitMerge, LayoutDashboard, LogOut, Plus, Receipt, Search, Settings, ShieldCheck, SlidersHorizontal, Users, X } from 'lucide-react'

const C = { petrol:'#176b6b', steel:'#55758a', ink:'#17252d', muted:'#879197', ok:'#4f806d', warn:'#a57d37', risk:'#ad6255' }
const pipeline = [['Lead',8,'#718b9a'],['Conflict check',5,C.warn],['Approved',11,C.steel],['Active',47,C.ok],['Review',9,'#777d92'],['Completed',23,'#628b7d'],['Closed',31,'#526a75']] as const
const workload = [['AK','Andile Khumalo',14],['ND','Nothando Dlamini',11],['SM','Sipho Mokoena',9],['LN','Lindiwe Nkosi',7],['TS','Thabo Sithole',6],['ZM','Zanele Mthembu',4]] as const
const activity = [['Nothando Dlamini','created Matter M-2024-0391 for Sasol Ltd','8m',FileText,C.steel],['System','conflict check completed — no conflicts found','22m',GitMerge,C.ok],['Sipho Mokoena','time entry logged — 3.5h on M-2024-0367','55m',Activity,C.muted],['Zanele Mthembu','client contact added — Standard Bank Treasury','2h',Users,C.petrol],['Andile Khumalo','approved Matter M-2024-0388 for commencement','3h',CheckCircle2,C.ok],['Lindiwe Nkosi','document NDA-Draft-v3.docx marked high-risk by AI','5h',AlertTriangle,C.risk]] as const
const revenue = [{m:'Feb',v:1477000},{m:'Mar',v:1846000},{m:'Apr',v:2074000},{m:'May',v:2300000},{m:'Jun',v:2582000},{m:'Jul',v:2840000}]
const nav = [[LayoutDashboard,'Dashboard'],[BriefcaseBusiness,'Matters'],[Users,'Clients'],[GitMerge,'Conflicts'],[FileText,'Documents'],[ShieldCheck,'FICA'],[Receipt,'Billing'],[FileSearch,'Audit'],[BarChart3,'Reports']] as const
function money(v:number){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(v)}
function Panel({title,accent=C.petrol,children}:{title:string;accent?:string;children:React.ReactNode}){return <section className="paper-panel"><div className="paper-panel-head"><i style={{background:accent}}/>{title}</div><div className="paper-panel-body">{children}</div></section>}
function Metric({label,value,color=C.ink,active=false,onClick}:{label:string;value:string|number;color?:string;active?:boolean;onClick:()=>void}){return <button className="paper-metric" style={{borderLeftColor:active?color:'transparent'}} onClick={onClick}><span style={{color:active?color:undefined}}>{label}</span><b style={{color}}>{value}</b><ArrowRight size={12}/></button>}
function PipelinePanel({ onAction }: { onAction: () => void }) {
 return <Panel title={`Matter pipeline · ${pipeline.reduce((a,p)=>a+p[1],0)} total`}><div>
  <div>{pipeline.map(([n,v,c]) => React.createElement('div',{className:'paper-pipe-row',key:n},
   React.createElement('span',{className:'paper-pipe-label'},React.createElement('i',{style:{background:c}}),n),
   React.createElement('div',{className:'paper-bar'},React.createElement('i',{style:{width:`${Number(v)/134*100}%`,background:c}}))
  ))}</div>
  <button className="paper-footer-link" onClick={onAction}>View all matters<ArrowRight size={12} style={{marginLeft:'auto'}}/></button>
 </div></Panel>
}
function RevenuePanel() {
 return <Panel title="Revenue · 6-month trend" accent={C.steel}>
  <div className="paper-revenue-head"><div><strong>{money(2840000)}</strong><span>↑ YTD</span></div><div><b>{money(620000)}</b><small>OUTSTANDING</small></div></div>
  <div className="paper-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenue}><defs><linearGradient id="paperFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={C.petrol} stopOpacity=".24"/><stop offset="100%" stopColor={C.petrol} stopOpacity="0"/></linearGradient></defs><XAxis dataKey="m" tick={{fill:C.muted,fontSize:9}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#17252d',border:'0',fontSize:10,color:'#f7f4eb'}} formatter={(v)=>money(Number(v))}/><Area dataKey="v" stroke={C.petrol} fill="url(#paperFill)" strokeWidth={2} dot={false}/></AreaChart></ResponsiveContainer></div>
 </Panel>
}
function PaperTealDashboard(){
 const [selected,setSelected]=useState('Dashboard'); const [dismissed,setDismissed]=useState(false); const [toast,setToast]=useState('')
 const notify=(text:string)=>{setToast(text);window.setTimeout(()=>setToast(''),2200)}
 const action=()=>notify('Opening workspace queue')
 return <div className="apz-paper-teal"><div className="paper-shell">
  <aside className="paper-sidebar"><div className="paper-brand"><div className="paper-brand-mark"/><div><b>APZ Legal</b><small>MATTER MANAGEMENT</small></div></div><div className="paper-profile"><div className="paper-avatar">AK</div><div><b>Andile Khumalo</b><small>Managing Partner</small></div><ChevronDown size={14} style={{marginLeft:'auto'}}/></div><div className="paper-search"><Search size={13}/><span>Search workspace</span><kbd>⌘K</kbd></div><nav className="paper-nav">{nav.map(([Icon,label],i)=><button key={label} className={selected===label?'active':''} onClick={()=>{setSelected(label);notify(`${label} selected`)}}><Icon size={15}/><span>{label}</span>{label==='Conflicts'&&<em>5</em>}{label==='Documents'&&<em>12</em>}{label==='FICA'&&<em style={{color:C.risk}}>3</em>}</button>)}</nav><div className="paper-side-bottom"><button className="paper-new" onClick={()=>notify('New matter form ready')}><Plus size={14}/>New matter</button><div className="paper-settings"><button onClick={()=>notify('Settings selected')}><Settings size={14}/>Settings</button><button onClick={()=>notify('Signed out')} aria-label="Log out"><LogOut size={14}/></button></div></div></aside>
  <main className="paper-content"><header className="paper-header"><div><h1>Good morning, Andile</h1><p>Monday, 18 November 2024 <span>·</span> Firm overview</p></div><div className="paper-header-actions"><button className="paper-icon-button" onClick={()=>notify('Calendar opened')}><CalendarDays size={15}/></button><button className="paper-icon-button" onClick={()=>notify('Notifications opened')}><Bell size={15}/><i/></button><button className="paper-filter" onClick={()=>notify('Department filter opened')}><SlidersHorizontal size={13}/>All departments<ChevronDown size={12}/></button></div></header>
  <div className="paper-main"><div className="paper-context"><div><span className="paper-eyebrow">OPERATIONS OVERVIEW</span><p>Review the firm’s open work and exceptions before your first meeting.</p></div><button className="paper-date" onClick={()=>notify('Showing today')}>Today<ChevronDown size={12}/></button></div>
  {!dismissed&&<div className="paper-alert"><div className="paper-alert-head"><Bell size={14} color={C.risk}/><b>6 items requiring your attention</b><span className="paper-badge risk">3 critical</span><span className="paper-badge warn">3 warnings</span><button onClick={()=>setDismissed(true)} aria-label="Dismiss alerts"><X size={14}/></button></div><div className="paper-alert-items">{[['1 client blocked — FICA incomplete',C.risk],['2 expired FICA documents',C.risk],['2 matters flagged at risk',C.risk],['2 AI documents flagged high-risk',C.warn],['FICA at 87% — below threshold',C.warn],['4 tasks overdue',C.warn]].map(([t,c])=><button className="paper-alert-item" key={t as string} onClick={action}><i style={{background:c as string}}/><span style={{color:c as string}}>{t}</span><ArrowRight size={12}/></button>)}</div></div>}
  <div className="paper-kpis">{[[BriefcaseBusiness,'Active matters','47','+4 from last month',C.petrol],[GitMerge,'Conflict checks','5','Awaiting review',C.warn],[ShieldCheck,'FICA compliant','87%','Firm threshold 90%',C.warn],[CircleDollarSign,'Unbilled hours','38h','Across active matters',C.petrol],[ClipboardCheck,'Overdue tasks','4','Requires attention',C.risk]].map(([Icon,label,value,sub,color])=>{const KpiIcon=Icon as React.ElementType; return <button className="paper-kpi" key={String(label)} onClick={action}><div className="paper-kpi-label"><KpiIcon size={13} style={{color:color as string}}/>{String(label)}</div><strong style={{color:color as string}}>{String(value)}</strong><small>{String(sub)}</small></button>})}</div>
  <div className="paper-grid"><div className="paper-col"><PipelinePanel onAction={action}/><RevenuePanel/></div>
  <div className="paper-col"><Panel title="Requires approval" accent={C.warn}>{[['Matters awaiting commencement',6,C.steel],['Conflict checks pending',5,C.warn],['Documents awaiting approval',12,C.warn],['AI high-risk documents',2,C.risk],['Matters flagged at risk',2,C.risk]].map(([label,value,color])=><Metric key={label as string} label={label as string} value={value as number} color={color as string} active onClick={action}/>)}</Panel><Panel title="Team workload">{workload.map(([initials,name,count])=><div className="paper-person" key={name}><div className="paper-avatar">{initials}</div><div className="paper-person-main"><div><span>{name}</span><b>{count}</b></div><div className="paper-bar"><i style={{width:`${Number(count)/14*100}%`,background:C.petrol}}/></div></div></div>)}</Panel></div>
  <div className="paper-col"><Panel title="Recent activity" accent={C.steel}><div>{activity.map(([who,desc,time,Icon,color])=><div className="paper-activity-row" key={desc}><Icon size={13} style={{color}}/><p><b>{who}</b> {desc}</p><time>{time}</time></div>)}</div><div className="paper-quick">{['All matters','Conflicts','Billing','Audit log'].map(x=><button key={x} onClick={()=>notify(`${x} opened`)}>{x}</button>)}</div></Panel></div></div></div></main></div>{toast&&<div className="paper-toast">{toast}</div>}</div>
}
export { PaperTealDashboard }
export default PaperTealDashboard